### ISSUE TITLE
RuntimeError: Error building extension 'DCN'

### ISSUE THREAD

**Issue by D4vx** [zhou13/neurvps#14]
Hi,

I have followed the environment instructions multiple times and I am unable to get past the following error:

Evaluating against the pre-trained Scannet checkpoint yeilds the following error:

`
{   'io': {   'augmentation_level': 2,
              'datadir': 'data/scannet-vp',
              'dataset': 'ScanNet',
              'focal_length': 2.408333333333333,
              'logdir': 'logs/',
              'num_vpts': 3,
              'num_workers': 6,
              'resume_from': 'logs/190522-040435-de95f53-scannet-conic6',
              'tensorboard_port': 0,
              'validation_debug': 240,
              'validation_interval': 24000},
    'model': {   'backbone': 'stacked_hourglass',
                 'batch_size': 6,
                 'conic_6x': True,
                 'depth': 4,
                 'fc_channel': 1024,
                 'im2col_step': 32,
                 'multires': <BoxList: [0.02004838034795, 0.0774278195486317, 0.299564810864565]>,
                 'num_blocks': 1,
                 'num_stacks': 1,
                 'num_steps': 4,
                 'output_stride': 4,
                 'smp_multiplier': 2,
                 'smp_neg': 1,
                 'smp_pos': 1,
                 'smp_rnd': 3,
                 'upsample_scale': 1},
    'optim': {   'amsgrad': True,
                 'lr': 0.0001,
                 'lr_decay_epoch': 3,
                 'max_epoch': 36,
                 'name': 'Adam',
                 'weight_decay': 1e-05}}
Let's use 1 GPU(s)!
Detected CUDA files, patching ldflags
Emitting ninja build file /home/dave/code/neurvps/neurvps/models/cpp/build/DCN/build.ninja...
Building extension module DCN...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /usr/local/cuda-9.0/bin/nvcc --generate-dependencies-with-compile --dependency-output deform_conv_cuda.cuda.o.d -DTORCH_EXTENSION_NAME=DCN -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/dave/anaconda3/envs/neuvps/lib/python3.8/site-packages/torch/include -isystem /home/dave/anaconda3/envs/neuvps/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/dave/anaconda3/envs/neuvps/lib/python3.8/site-packages/torch/include/TH -isystem /home/dave/anaconda3/envs/neuvps/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-9.0/include -isystem /home/dave/anaconda3/envs/neuvps/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/dave/code/neurvps/neurvps/models/cpp/deform_conv_cuda.cu -o deform_conv_cuda.cuda.o 
FAILED: deform_conv_cuda.cuda.o 
/usr/local/cuda-9.0/bin/nvcc --generate-dependencies-with-compile --dependency-output deform_conv_cuda.cuda.o.d -DTORCH_EXTENSION_NAME=DCN -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/dave/anaconda3/envs/neuvps/lib/python3.8/site-packages/torch/include -isystem /home/dave/anaconda3/envs/neuvps/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/dave/anaconda3/envs/neuvps/lib/python3.8/site-packages/torch/include/TH -isystem /home/dave/anaconda3/envs/neuvps/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-9.0/include -isystem /home/dave/anaconda3/envs/neuvps/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/dave/code/neurvps/neurvps/models/cpp/deform_conv_cuda.cu -o deform_conv_cuda.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/dave/anaconda3/envs/neuvps/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1667, in _run_ninja_build
    subprocess.run(
  File "/home/dave/anaconda3/envs/neuvps/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./eval.py", line 185, in <module>
    main()
  File "./eval.py", line 86, in main
    model = neurvps.models.VanishingNet(
  File "/home/dave/code/neurvps/neurvps/models/vanishing_net.py", line 23, in __init__
    self.anet = ApolloniusNet(output_stride, upsample_scale)
  File "/home/dave/code/neurvps/neurvps/models/vanishing_net.py", line 90, in __init__
    self.conv00 = ConicConv(32, 32)
  File "/home/dave/code/neurvps/neurvps/models/conic.py", line 12, in __init__
    self.deform_conv = DeformConv(
  File "/home/dave/code/neurvps/neurvps/models/deformable.py", line 133, in __init__
    DCN = load_cpp_ext("DCN")
  File "/home/dave/code/neurvps/neurvps/models/deformable.py", line 24, in load_cpp_ext
    ext = load(
  File "/home/dave/anaconda3/envs/neuvps/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1079, in load
    return _jit_compile(
  File "/home/dave/anaconda3/envs/neuvps/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1292, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/dave/anaconda3/envs/neuvps/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1404, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/dave/anaconda3/envs/neuvps/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'DCN'
`

Python 3.8.5
Pytorch / torchvision / torchaudio all installed for Python > Linux > Conda > Cuda 11.1
Nvidia-SMI 460.56
CUDA Version 11.2

The same with the other reported issues - I have searched online for a solution but have not been able to get it working. Any pointers / ideas / solutions would be great!

Thanks

**Comment by zhou13** [comment]
It might be because your CUDA version (found by pytorch) is not 11.1. Google says that `-generate-dependencies-with-compile` was added in CUDA 10.2.

**Comment by D4vx** [comment]
Curious! I will dig into this some more - thanks for the pointer, I will update this ticket if when I make some progress.

**Comment by D4vx** [comment]
You were indeed correct - due to having multiple versions of nvcc on my system the exports were a muddle.
I have since updated these and am now able to get past this issue.

for anyone else wondering about the solve here - update the LD_LIBRARY_PATH and the associated PATH reference to match the correctly installed version of cuda. For me this was adding /usr/local/cuda-11.3/bin to PATH and /usr/local/cuda-11.3/lib64 to LD_LIBRARY_PATH

Thanks
