### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by wenyang94** [zhou13/neurvps#2]
Hi zhou,

Thanks for sharing your code.

I have installed all the prerequisite packages. When I try to evaluate your pretrained model, errors below occur. Any idea?

Traceback (most recent call last):
  File "/home/yw/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 759, in _build_extension_module
    ['ninja', '-v'], stderr=subprocess.STDOUT, cwd=build_directory)
  File "/home/yw/anaconda3/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/home/yw/anaconda3/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval.py", line 179, in <module>
    main()
  File "eval.py", line 83, in main
    model, C.model.output_stride, C.model.upsample_scale
  File "/home/yw/nets/neurvps/neurvps/models/vanishing_net.py", line 23, in __init__
    self.anet = ApolloniusNet(output_stride, upsample_scale)
  File "/home/yw/nets/neurvps/neurvps/models/vanishing_net.py", line 90, in __init__
    self.conv00 = ConicConv(32, 32)
  File "/home/yw/nets/neurvps/neurvps/models/conic.py", line 19, in __init__
    bias=bias,
  File "/home/yw/nets/neurvps/neurvps/models/deformable.py", line 132, in __init__
    DCN = load_cpp_ext("DCN")
  File "/home/yw/nets/neurvps/neurvps/models/deformable.py", line 29, in load_cpp_ext
    build_directory=tar_dir,
  File "/home/yw/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 514, in load
    with_cuda=with_cuda)
  File "/home/yw/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 682, in _jit_compile
    _build_extension_module(name, build_directory)
  File "/home/yw/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 765, in _build_extension_module
    name, error.output.decode()))
RuntimeError: Error building extension 'DCN': [1/3] c++ -MMD -MF deform_conv.o.d -DTORCH_EXTENSION_NAME=DCN -I/home/yw/.local/lib/python3.7/site-packages/torch/lib/include -I/home/yw/.local/lib/python3.7/site-packages/torch/lib/include/TH -I/home/yw/.local/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/yw/anaconda3/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /home/yw/nets/neurvps/neurvps/models/cpp/deform_conv.cpp -o deform_conv.o
FAILED: deform_conv.o 
c++ -MMD -MF deform_conv.o.d -DTORCH_EXTENSION_NAME=DCN -I/home/yw/.local/lib/python3.7/site-packages/torch/lib/include -I/home/yw/.local/lib/python3.7/site-packages/torch/lib/include/TH -I/home/yw/.local/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/yw/anaconda3/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /home/yw/nets/neurvps/neurvps/models/cpp/deform_conv.cpp -o deform_conv.o
In file included from /home/yw/nets/neurvps/neurvps/models/cpp/deform_conv.cpp:1:0:
/home/yw/nets/neurvps/neurvps/models/cpp/deform_conv_cpu.h:2:10: fatal error: torch/extension.h: No such file or directory
 #include <torch/extension.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
[2/3] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=DCN -I/home/yw/.local/lib/python3.7/site-packages/torch/lib/include -I/home/yw/.local/lib/python3.7/site-packages/torch/lib/include/TH -I/home/yw/.local/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/yw/anaconda3/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options '-fPIC' -std=c++11 -c /home/yw/nets/neurvps/neurvps/models/cpp/deform_conv_cuda.cu -o deform_conv_cuda.cuda.o
FAILED: deform_conv_cuda.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=DCN -I/home/yw/.local/lib/python3.7/site-packages/torch/lib/include -I/home/yw/.local/lib/python3.7/site-packages/torch/lib/include/TH -I/home/yw/.local/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/yw/anaconda3/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options '-fPIC' -std=c++11 -c /home/yw/nets/neurvps/neurvps/models/cpp/deform_conv_cuda.cu -o deform_conv_cuda.cuda.o
In file included from /home/yw/nets/neurvps/neurvps/models/cpp/deform_conv_cuda.cu:2:0:
/home/yw/nets/neurvps/neurvps/models/cpp/deform_im2col_cuda.cuh:6:10: fatal error: ATen/cuda/CUDAContext.h: No such file or directory
 #include <ATen/cuda/CUDAContext.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

**Comment by zhou13** [comment]
It seems that your gcc cannot find `<torch/extension.h>`, indicating that your PyTorch installation has some problems. It should be in your `/home/yw/.local/lib/python3.7/site-packages/torch/lib/include` (or similar places) if installed correctly.

**Comment by wenyang94** [comment]
What is your pytorch version? I created your environment using conda, but I do not find the missing files. Though I download the files from pytorch repo, it still has the same errors.

**Comment by wenyang94** [comment]
It is because I previouly install pytorch 0.4 using pip and it was installed into .local folder. After I delete it, everything works. Thanks!
