### ISSUE TITLE
'Box' object has no attribute 'from_yaml'

### ISSUE THREAD

**Issue by sepulm01** [zhou13/neurvps#24]
Hi, I got this erro message executing this command:

python eval.py -d 0 logs/scanet/config.yaml logs/scanet/better-result.pth.tar

Error:
Traceback (most recent call last):
  File "/home/martin/Proyectos/neurvps/neurvps/box.py", line 412, in __getitem__
    value = super(Box, self).__getitem__(item)
KeyError: 'from_yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/martin/Proyectos/neurvps/neurvps/box.py", line 492, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
  File "/home/martin/Proyectos/neurvps/neurvps/box.py", line 419, in __getitem__
    raise BoxKeyError(str(err))
neurvps.box.BoxKeyError: "'from_yaml'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/martin/Proyectos/neurvps/neurvps/box.py", line 494, in __getattr__
    value = object.__getattribute__(self, item)
AttributeError: 'Box' object has no attribute 'from_yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/martin/Proyectos/neurvps/eval.py", line 185, in <module>
    main()
  File "/home/martin/Proyectos/neurvps/eval.py", line 58, in main
    C.update(C.from_yaml(filename=config_file))
  File "/home/martin/Proyectos/neurvps/neurvps/box.py", line 511, in __getattr__
    raise BoxKeyError(str(err))
neurvps.box.BoxKeyError: "'Box' object has no attribute 'from_yaml'"

SO : Ubuntu 22.04
Eviroment: venv with Python 3.10.6

**Comment by zhou13** [comment]
Did you have `pyyaml` installed?
